[tools]
go = "1.26"
golangci-lint = "2.5"
nomad-pack = "0.4"
shellcheck = "0.11"
nomad = "2"

[tasks.pre-commit]
description = "Run pre-commit"
run = "pre-commit run --all-files --color always"

[tasks.lint]
description = "Run golangci-lint"
alias = "l"
run = "mise run pre-commit golangci-lint-full"

[tasks.build]
description = "Build the project"
alias = "b"
run = "go build -o np ./cmd/np"

[tasks.test]
description = "Run tests"
alias = "t"
run = "go test ./..."
